### ISSUE TITLE
Use fonts instead of icons

### ISSUE THREAD

**Issue by 24mu13** [jankapunkt/latexcv#1]
https://coderwall.com/p/r67dyq/using-font-awesome-with-xe-latex

**Comment by jankapunkt** [comment]
Potentially agree, but with one exception.
It would be great to have FA (or any other font based icon set) without the need for xetex. A solution that works using pdfLatex is a definite candidate for a merge.
Best, Jan

**Comment by jankapunkt** [comment]
Merged via #2
