### ISSUE TITLE
Please  add chinese language  support

### ISSUE THREAD

**Issue by xuanyuanaosheng** [jankapunkt/latexcv#19]

**Comment by jankapunkt** [comment]
Hi, thank you for your interest in this package. I am not familiar with supporting other languages yet. Do you know a LaTeX project on GitHub that successfully supports multiple languages? If so, could you please add a link to it, so I can check on it?

@community if anyone has already experience with encoding to support multiple languages feel free toeave a PR

**Comment by jankapunkt** [comment]
@xuanyuanaosheng I forgot to mention that you may also add a description of how the current templates do not support Chinese language. Does the compilation throw any errors or is the generated document layout broken?

**Comment by xuanyuanaosheng** [comment]
> Hi, thank you for your interest in this package. I am not familiar with supporting other languages yet. Do you know a LaTeX project on GitHub that successfully supports multiple languages? If so, could you please add a link to it, so I can check on it?
> 
@jankapunkt 
 I have found a Project on Github:  https://github.com/billryan/resume/tree/zh_CN.

The ShareLaTeX address is https://www.sharelatex.com/templates/556b27cf0d23e5a8117053d9

**Comment by jankapunkt** [comment]
@xuanyuanaosheng I checked the project [but it requires xelatex](https://github.com/billryan/resume/blob/zh_CN/resume-zh_CN.tex#L1), which is an anit-requirement of this package (I created this package with the intention of compiling all templates without the need to install xetex or luatex or koma script.

However, I found a tex.stackexchange discussion with [an answer that also shows a pdflatex-only example](https://tex.stackexchange.com/questions/17611/how-does-one-type-chinese-in-latex) and I will check into it.

@community If there is anyone with experience in writing Chinese LaTeX only usng pdflatex please let me know if there are any known issues regarding encoding, fonts etc.

**Comment by jankapunkt** [comment]
@xuanyuanaosheng  I found a potential solution and I will create a new branch for it. Once the branch is there I'd like you to check it out and test, if it all compiles for you.

**Comment by xuanyuanaosheng** [comment]
> @xuanyuanaosheng I checked the project [but it requires xelatex](https://github.com/billryan/resume/blob/zh_CN/resume-zh_CN.tex#L1), which is an anit-requirement of this package (I created this package with the intention of compiling all templates without the need to install xetex or luatex or koma script.
@jankapunkt I also find  some solutions on google, the links：
https://www.overleaf.com/learn/latex/Chinese
https://jdhao.github.io/2018/03/29/latex-chinese.zh/ 

But a good way to support different country' language is using xelatex.

**Comment by xuanyuanaosheng** [comment]
> @xuanyuanaosheng I found a potential solution and I will create a new branch for it. Once the branch is there I'd like you to check it out and test, if it all compiles for you.

@jankapunkt  OK. I will check it out and test it.  Thanks.

**Comment by jankapunkt** [comment]
Can you please checkout the new cjk branch: https://github.com/jankapunkt/latexcv/tree/cjk

Configuration of the cjk environment should be really easy (two additional lines of code in the template files). The setup is documented here: https://github.com/jankapunkt/latexcv/blob/cjk/cjk/README.md

If there are any errors please post them here. If characters are missing or not correctly displayed please describe with detail.

**Comment by jankapunkt** [comment]
@xuanyuanaosheng any success with the setup?

**Comment by jankapunkt** [comment]
I merged the PR #20 so this is now on master branch. Please leave an issue if there is anything preventing you from compiling using CJK.

**Comment by xuanyuanaosheng** [comment]
@jankapunkt  Sorry to reply so late.  I  have tested it on ubuntu 18.04 follow your guide, it  has worked.   Thanks !
