### ISSUE TITLE
CV Timeline

### ISSUE THREAD

**Issue by phlndrwd** [jankapunkt/latexcv#22]
Thank you for these CV templates! They are very creative.

I am interested in the infographics template. Am I correct in saying that the timeline does not appear to display all of the parameters that are input to a `cvevent`? When I rebuild your example TEX file, the PDF appears just like yours, but the comments in the timeline file seem to suggest there may be features missing from the rendered result.

Unfortunately, I'm far from being as accomplished as you with LaTeX, so any input would be greatly appreciated.

Cheers,
Phil

**Comment by jankapunkt** [comment]
Thank you @phlndrwd for this issue. I think this has already been mentioned before and I will check it out when there is some time left and corect the documentation or fix it, if it's a bug.

If someone else wants to open a PR for this, they are very welcome!

**Comment by jankapunkt** [comment]
this is now implemented in imfographics 2, see #46

I will close this. feel free to reopen if this not a valid solution
