### ISSUE TITLE
Centering item labels with text

### ISSUE THREAD

**Issue by CsatiZoltan** [jankapunkt/latexcv#24]
`\cvevent` uses *\cdot* to enlist items. This has the drawback that it is not positioned at the center of a capital letter. Maybe using the *itemize* environment would help (*\cdot* could be simulated by decreasing the size of the bullet). Alternatively, the height of the *\cdot* could be raised.

**Comment by jankapunkt** [comment]
Hi @CsatiZoltan which template you are referring to? I am usually using a `tabular*` in the `cvevent` command, so I am not sure where a `cdot` is in use there. Can you please show me the line? 

The only `cdot` I am using is in the footers and headers to separate the horizontal content. Is this what you are referring to?

**Comment by CsatiZoltan** [comment]
@jankapunkt Sure, for instance [this line](https://github.com/jankapunkt/latexcv/blob/ba351ac3b25d0aca6680e4fee5b82100b2cf4a8d/classic/main.tex#L253) and the next one in the classic template.

**Comment by jankapunkt** [comment]
@CsatiZoltan I see, this template was one of the first ones, I have created. If you want to change it to using `itemize`, feel free to open a PR but please try to keep the layout simple and on one page. I will have the next days some time for review.

**Comment by jankapunkt** [comment]
@CsatiZoltan just a friendly ping. Are you interested in providing a PR?

**Comment by CsatiZoltan** [comment]
Sorry for the long delay, I was/am very busy these days. I would like to implement this but I have no free time, so I would say I cannot provide a PR. At least not in the near future.
