### ISSUE TITLE
Feature suggestion: Environment Variables

### ISSUE THREAD

**Issue by Jonty16117** [jankapunkt/latexcv#28]
I think it would be cool to add a type of b/w and a colour version for each available template. It would be very helpful for printing the resumes.

**Comment by jankapunkt** [comment]
Hi @Jonty16117 you can actually set in each template the colors. Just check out the code, there is in each template a section where all the used colors are defined. If you want a black white version you just need to tweak the colors with some harmonizing greyscale values.

However, there maybe an option to use colors based on some compiler flags. Now I have not investigated into the pdflatex compiler, if I can pass custom flags but something like `--greyscale` would be cool. What do you think?

**Comment by Jonty16117** [comment]
`--greyscale` flag seems like a good solution to me. 💯

**Comment by jankapunkt** [comment]
I found a solution using environment variables, however it complicates the scripts unnecessarily if we integrate the code for this in every template. I'd rather provide this feature as an entirely optional script to include in combination with a short example in a wiki entry. What do you think?

**Comment by jankapunkt** [comment]
Please check on the PR #29 (I added you to the collaborators) and create a review using the gh review function.

**Comment by jankapunkt** [comment]
Will drop this for now, since it makes things just more complicated

**Comment by jankapunkt** [comment]
@Jonty16117 feel free to reopen and discuss a potential solution

**Comment by Jonty16117** [comment]
Sure...thanks😊
