### ISSUE TITLE
Classic : more lines for experience section

### ISSUE THREAD

**Issue by Sophalsun888** [jankapunkt/latexcv#30]
Hello M Jan Küster
Thank you for this wonderful job.

About the classic resume, how can I add more lines under an experience , it seems to be limited at 2 lines !! 

Thanks a lot for your help

Sophal SUN

**Comment by jankapunkt** [comment]
Hi @Sophalsun888 thank you,

the makro `\cvevent` is limited to two lines *in it's current definition* but that does not prevent you from extending it:

```latex
% creates a stretched box as cv entry headline followed by two paragraphs about 
% the work you did
% param 1:	event time i.e. 2014 or 2011-2014 etc.
% param 2:	event name (what did you do?)
% param 3:	institution (where did you work / study)
% param 4:	what was your position
% param 5:	some words about your contributions
%
\newcommand{\cvevent}[5]
{

\begin{tabular*}{1\textwidth}{p{13.6cm}  x{3.9cm}}
	\textbf{#2} - \textcolor{bgcol}{#3} &   \vspace{2.5pt}\textcolor{sectcol}{#1}
\end{tabular*}

\vspace{-8pt}
\textcolor{softcol}{\hrule}
\vspace{6pt}

  $\cdot$ #4\\[3pt]
  $\cdot$ #5\\[6pt]

}
```

as you can see the last two parameters `#4` and `#5` represent these two lines. If you want more than two lines, you would have to extend the max. args from `[5]` to `[6]` and add another parameter:

```latex
\newcommand{\cvevent}[6]
{

\begin{tabular*}{1\textwidth}{p{13.6cm}  x{3.9cm}}
	\textbf{#2} - \textcolor{bgcol}{#3} &   \vspace{2.5pt}\textcolor{sectcol}{#1}
\end{tabular*}

\vspace{-8pt}
\textcolor{softcol}{\hrule}
\vspace{6pt}

  $\cdot$ #4\\[3pt]
  $\cdot$ #5\\[3pt]
  $\cdot$ #6\\[6pt]

}
```

Now here is the thing: You can change this in any way you want, for example could you replace the bullets with a single parameter, and pass an item-list (using `itemize`:

```latex
\newcommand{\cvevent}[4]
{

\begin{tabular*}{1\textwidth}{p{13.6cm}  x{3.9cm}}
	\textbf{#2} - \textcolor{bgcol}{#3} &   \vspace{2.5pt}\textcolor{sectcol}{#1}
\end{tabular*}

\vspace{-8pt}
\textcolor{softcol}{\hrule}
\vspace{6pt}

#4
}
```
which you then call via:

```latex
\cvevent{2016 - present}{Scientific Employee / PhD Student}{University of XYZ}
{\begin{itemite}
  \item did this and that
  \item and this and this
  \item solved a lot of things
\end{itemite}}
```

I will generate a wiki entry out of this so this question has a general answer. Feel free to reopen if this does not answer your question in any way.

**Comment by jankapunkt** [comment]
Wiki entry added at: https://github.com/jankapunkt/latexcv/wiki/Extending-cvevent-Macro

**Comment by olimanger** [comment]
Alternatively, you could add a flexible number of arguments with the "shopping list"-idea to the macro like that:

`\makeatletter
\newcommand{\cvsubevent}[1]{$\cdot$  #1 \\[3pt] \checknextarg}
\newcommand{\checknextarg}{\@ifnextchar\bgroup{\gobblenextarg}{ }}
\newcommand{\gobblenextarg}[1]{$\cdot$ #1 \\[3pt]\@ifnextchar\bgroup{\gobblenextarg}{ }}
`

and call this macro by
`\cvsubevent{the one and only subpoint}`

or 

`\cvsubevent{first out of many}{second and still not last}{third subpoint}{subpoint number 4}{and the fifth and final subpoint}`

Greetings,
Oli

**Comment by Sophalsun888** [comment]
dear Jan ,

thanks a lot for your answer , I really appreciate .

you help me a lot

best regards

Sophal SUN
