### ISSUE TITLE
Clarification of license conditions

### ISSUE THREAD

**Issue by cj-wx91** [jankapunkt/latexcv#33]
Hi,

thanks for the great-looking templates.
The attached MIT license says

"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

Would that mean that the copyright also has to be included in the final generated PDF?

**Comment by jankapunkt** [comment]
@cj-wx91 does it answer your question? If so, please close the issue, otherwise feel free to ask anything.
