### ISSUE TITLE
How to create extra page

### ISSUE THREAD

**Issue by mjnajafi** [jankapunkt/latexcv#35]
it's my pleasure to use your CV classic template.
I have a question about latex programming.
when I replace my text on the template, the lines go under the page and some parts will be disappeared.
How can I go to another page and continue the previous part?

Thank you in advance for your guidance.
M. Javad

**Comment by jankapunkt** [comment]
Hi @mjnajafi sorry for late response. Which template excactly? Most of them are 1-page templates. They were not designed with multipage in mind. However we can make that work on some of them.

**Comment by mjnajafi** [comment]
I mean Sidebar template. 
I would be than happy to let me know how to use it in multipage.

**Comment by jankapunkt** [comment]
You can actually check the `sidebarleft` template which is already multipage. If it doesn't work please comment with what exactly doesn't work and we may find a solution that can work for everyone.

If you make it work it would be great to open a PR so all can benefit from it :-)

**Comment by jankapunkt** [comment]
@mjnajafi did it help to take a look at `sidebarleft`?

**Comment by mjnajafi** [comment]
> @mjnajafi did it help to take a look at `sidebarleft`?

well, sidebarleft works correctly. But I want to use the sidebar template. 
I was trying to use \newpage command but it did not work.
I was wondering if you could convert the sidebar template into two pages.

appreciate the time you take

**Comment by jankapunkt** [comment]
@mjnajafi I was referring to the sidebar-left code, because it shows you how to implement it for multipages. Simply adding newlines will break the layout, which is why it uses several environments to fulfill this need. I will make a wiki entry for it.

**Comment by jankapunkt** [comment]
Please take a look at the [wiki](https://github.com/jankapunkt/latexcv/wiki) :-)
