### ISSUE TITLE
! LaTeX Error: File `xifthen.sty' not found.

### ISSUE THREAD

**Issue by theharshwardhan** [jankapunkt/latexcv#36]
Can't locate the above file.

**Comment by jankapunkt** [comment]
Hi @theharshwardhan can you please provide more context? Which Template did you use? Which OS and LaTeX distribution? What commands did you run?

**Comment by theharshwardhan** [comment]
I was using the "modern" template and tried to compile it using TeX 3.14159265 (TeX Live 2019/Debian). My OS is Ubuntu 20.04.

```
$ cd modern
$ pdflatex main.tex

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)

! LaTeX Error: File `xifthen.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:

**Comment by jankapunkt** [comment]
Hey @theharshwardhan  I used `synaptic` to use through my packages and found, that `xifthen` is part of `texlive-latex-extra`. Can you check, if you have this package installed? It should be available on Debian, too and be installable via the package manager.

**Comment by theharshwardhan** [comment]
Got it. Fixed the issue.

**Comment by jankapunkt** [comment]
Great to hear it! I will add a Wiki entry in order to make it easier for others in the future to instantly solve this issue.
