### ISSUE TITLE
More info on installation/packages needed

### ISSUE THREAD

**Issue by kiteloopdesign** [jankapunkt/latexcv#39]
Documentation says 

> You will need some minimal Texlive distrubution 

I installed both the "small" and "medium scheme" from texlive 2021 installer, but in both cases I am missing some packages needed to build the mordern CV. 

```
! LaTeX Error: File `xifthen.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 

! LaTeX Error: File `raleway.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/t1cmss.fd))

! LaTeX Error: File `moresize.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```
The pdf is produced but it does not look completely like the original. 

Maybe we can make use of that profile to pass it on to the installation process? Not sure how to do it, though, I will investigate

**Comment by SiliconKite** [comment]
Ok, so you pass on the profile included on this repo by running the installer with this option

`sudo ./install-tl -profile=./texlive.profile`

The instalation takes (!) 5GB (and my root partition ran out of space)

So, no, it does not look like you need a *minimal* latex instalation. By the way, this is why I am as of lately disgusting latex. It is completely crazy that you need to install such a crazy amount of packages just for a typesetting software. Hopefully LaTeX 3, if ever finished, will fix this issue (along with the extremely confussing installation doc and process)

**Comment by SiliconKite** [comment]
Can't get this to work. I give up. Its a shame we have a latex like this in 2021. They are losing users like crazy. Leaving here what I did in case it helps someone

latex has a package manager. Tried to find hte missing package
`tlmgr install texlive-latex-extra`

ok, so I will try to use the Fedora's latex. 
`sudo dnf install texlive`

pdf still not building properly. Let;s install some additional GB of crap:

`sudo dnf install texlive-collection-latexextra`

Looks like this is the missing package, and that installing it on the same folder as the .tex should do the trick

https://ctan.org/pkg/raleway

pdf build gives some other errors.

Ok, I had enough of this crap

**Comment by jankapunkt** [comment]
Hey @SiliconKite I'm sorry to hear that it became so complicated. The installation procedure was documented in 2014 and it seems that it is not up to date anymore.

Give me some time to set up a vm to play around a bit to update the installation.

I never used any manager from TexLive but always used synaptic to directly search for the deb package that contained the specific LaTex packages.

Note, raleway is part of texlive-fonts-extra (at least if you are using Ubuntu/Debian)

**Comment by SiliconKite** [comment]
I think the confussion comes from the *You will need some minimal Texlive distrubution* wording, when the full texlive installation is needed. It is 6.1GB. This is just crazy. Anyway, got it working now. Thanks

**Comment by Amir-Ahmad** [comment]
In case anyone comes across this project and is using Nix package manager, I've got a ~0.4GB install that I've put in my overlay.

```
mytexlive = self.texlive.combine {
    inherit (self.texlive)
      scheme-basic
      xifthen
      ifmtarg
      gillius
      xkeyval
      fontaxes
      moresize
      fontawesome
      multirow
      wrapfig
      float
      pgf
      transparent
      ;
  };
```

**Comment by jankapunkt** [comment]
@Amir-Ahmad thank you for this. Is it safe to replace the texlive file with these:

```
 scheme-basic
      xifthen
      ifmtarg
      gillius
      xkeyval
      fontaxes
      moresize
      fontawesome
      multirow
      wrapfig
      float
      pgf
      transparent
```

**Comment by jankapunkt** [comment]
Related PR is ongoing until this is resolved: https://github.com/jankapunkt/latexcv/pull/49

**Comment by Amir-Ahmad** [comment]
@jankapunkt that list was working for the theme sidebar, but I just tested on modern and it's not working (there are additional dependencies required).  

As for the replacing the texlive, I'm new to TexLive and Latex, so I'm not qualified to comment on that, sorry.

**Comment by jankapunkt** [comment]
@Amir-Ahmad mo worries, I am currently finding out a way to detect the packages that are used and then generate script from it. I first need to get `tlmgr` (texlive manager) get running with sudo then we can have a `schema-basic` plus these packages to have the very minimal build as desired.

See the #49  PR for ongoing progress
