### ISSUE TITLE
Add Institution to timeline entries

### ISSUE THREAD

**Issue by bhattaomatic** [jankapunkt/latexcv#4]
In the timeline, under the command \cvevent param 4 and 5 is not implemented. Will it be possible to get a short description of the event or experience right underneath the event within the timeline.

**Comment by jankapunkt** [comment]
Thank you for your comment.
Before I can help you, please clarify the following things:
* which cv template (classic, infographic, modern, two_column)
* do you want to know how the cvevent command works (documentation) or did you find a bug (bug) or a missing feature /enhancement)?

**Comment by bhattaomatic** [comment]
Thank you for the quick response.
Regarding your questions:
     - Currently I am working on the infographic cv template.
     - I figured out how the cvevent works and found out a possible enhancement of which the facility is     already available in the code, just the implementation is not available.

Basically what I am looking for in the timeline is a one line description of the work experience or project underneath the heading.

**Comment by jankapunkt** [comment]
Oh yes now I understand. This is a tricky one. I already added the institutions as parameters but left them out after I found it really hard to add them because the entries overlapped when the institution was included. If you find a way to add institutions without overlapping entries I would be grateful to merge this into this project.

**Comment by bhattaomatic** [comment]
Alright, I will give it a shot. Could you send me some references upon which you based this timeline?

**Comment by jankapunkt** [comment]
Hi @bhattaomatic I created some contribution guidelines, which also include some info and resources for developers: https://github.com/jankapunkt/latexcv/blob/master/CONTRIBUTING.md

**Comment by jankapunkt** [comment]
@bhattaomatic still interested in doing a PR for this issue?

**Comment by bhattaomatic** [comment]
Hi, I am preoccupied a bit with my job but yes I am still interested in this. Just that it is taking longer than I estimated. Hopefully, I will have something worth sharing in the next 15 to 20 days.

**Comment by jankapunkt** [comment]
@bhattaomatic will close this for now due to missing activity. However, you can reopen at any time if you want to come back to the issue.

**Comment by guillaumedsde** [comment]
Bumping this issue, I would be very interested in having a small paragraph below the a timeline entry as well as the institution.

For reference I have [implemented an "ugly" version of this here](https://gitlab.com/guillaumedsde/curriculum-vitae/blob/8607e45548b611c1f6fb51da38bf297a31c4d41c/timeline.tex#L71). This works OK-ish as long as the institution name is not too long and the text below the timeline entry is only one line short line

**Comment by jankapunkt** [comment]
@bhattaomatic  @guillaumedsde this is now implemented in imfographics 2, see  #46 

I will close this. feel free to reopen if this not a valid solution
