### ISSUE TITLE
Suggested fonts for the Infographics CV

### ISSUE THREAD

**Issue by aradnix** [jankapunkt/latexcv#42]
Hi, I'm trying to use your template in Overleaf and found that some of the suggested fonts don't allow you to place small caps text correctly so it falls back to the default font and it looks awful.

I was looking for options on the [LaTeX Font Catalogue](https://tug.org/FontCatalogue/sansseriffonts.html) website and found these sans-serif fonts that look great with this template.

```
\usepackage[defaultsans]{droidsans}
\usepackage{cmbright}
\usepackage[default]{raleway}
usepackage[default]{gillius}
\usepackage[sfdefault,condensed]{roboto} 
\usepackage[sfdefault]{AlegreyaSans}
\usepackage[familydefault]{Rosario}
\usepackage[sfdefault]{FiraSans}
\usepackage{libris}
\usepackage[sfdefault]{merriweather}
\usepackage{paratype}
\usepackage[sfdefault]{quattrocento}
\usepackage[default]{sourcesanspro}
\usepackage{venturis}
```

**Comment by jankapunkt** [comment]
If you want you can Open a pr to add them, please keep all but the used font commented
