### ISSUE TITLE
A better way, perhaps? to use FontAwesome

### ISSUE THREAD

**Issue by aradnix** [jankapunkt/latexcv#44]
Once again me with the topic of your Infographics CV template. I saw that you use some FontAwesome icons in svg within the template. However, I find it better to make use of the packages that already exist for LaTeX that allow you to include FontAwesome icons.

Because the engine in your templates usually is `pdflatex`, I suggest using the [fontawesome5](https://ctan.org/pkg/fontawesome5) package. With this package you have access to lots of FontAwesome 5 icons (not all, I think), but enough to enrich the CV with them almost everywhere because you can use them as if they were text.

This led me to try to redefine the way you work with icons in your template. The overall result seems good to me, although it's far from being perfect:

```
%\newcommand{\icons}{Font-Awesome-SVG-PNG/}	%path to your icon lib (we can forgot it)
\newcommand{\icon}[2]{\colorbox{thirdcol}{\includegraphics[height=#2]{\icons#1}}}	%icon shortcut
\renewcommand{\icon}[2]{\colorbox{thirdcol}{\textcolor{sectcol}{\Large{#1}}}} %better definition for add fontawesome icons directly from the package IMO
\newcommand{\icontext}[3]{ 						%icon with text shortcut
	\vcenteredhbox{\icon{#1}{#2}} \vcenteredhbox{\textcolor{textcol}{#3}}
}
```

The main advantage is that you can access hundreds of icons easily, the disadvantage is that as the icons have variable width, the tabbed result is not homogeneous and I have no idea right now how to solve it, but maybe you have a better idea about it.

**Comment by jankapunkt** [comment]
I have to investigate on fontawesome. At the time I wrote the infographics cv the latex package for it was not available but now it may be different.

**Comment by Lukas2112** [comment]
Instead of Fontawesome, the theme could be used Fork Awesome? https://forkaweso.me/Fork-Awesome/

**Comment by jankapunkt** [comment]
@Lukas2112 this is nice, however if I understand correctly, then we need a LaTeX package that wraps it
