### ISSUE TITLE
 installing TeX live package Enconuter error

### ISSUE THREAD

**Issue by LonYui** [jankapunkt/latexcv#48]
run $ install-tl --profile=<loaction> 
meet error message. The profile references a non-existing collection

**Comment by jankapunkt** [comment]
Can you please complete post a reproducible example that raises the error? Including which operating system you used and how you installed texlive

**Comment by d5269357812** [comment]
### desc
I follow the quick start. install the BasicTeX clone the project . then enconuter an error when installing TeX live package with .profile in the project.

env: 
- MacOs 14
- BasicTeX

### reproduce step:
``` bash
$ cd /usr/local/texlive/2021basic
$ install-tl --profile=<path of texlive.profile>
```

### error message

The profile references a non-existing collection: collection-pictures

![螢幕快照 2021-09-11 上午3 21 13](https://user-images.githubusercontent.com/9551862/132906517-78683f73-0112-431f-a185-64d50b17854e.png)

by the way ,as a begineer of latext, I spend some time (30 min) on figure out how to install the package. i think it will be better have some hint in the **How to build?**

**Comment by jankapunkt** [comment]
You can try to install without the profile file but it will install all packages. Maybe a package is not available anymore? I currently have no MacOSX available to reproduce but I can check this out with miktex on Windows.

**Comment by jankapunkt** [comment]
Related: #49
