### ISSUE TITLE
could latexcv support chinese string

### ISSUE THREAD

**Issue by hiDaDeng** [jankapunkt/latexcv#51]

**Comment by jankapunkt** [comment]
There is a wiki entry in the repository on how to setup Chinese character encoding. Does this help?

**Comment by hiDaDeng** [comment]
Got it! Thanks very much!!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jan ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jankapunkt/latexcv] could latexcv support chinese string (Issue #51)





 
There is a wiki entry in the repository on how to setup Chinese character encoding. Does this help?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
