### ISSUE TITLE
White line in name-header

### ISSUE THREAD

**Issue by jo-jstrm** [jankapunkt/latexcv#52]
First of all, thanskbs for prvoding such a well documented template! It was really easy to customize thanks to your documentations.

## Problem
My CV is based on your 'sidebar' template. I aligned the header box containing my name with the sidebar's top.
```
\begin{document}
\fcolorbox{white}{white}{\begin{minipage}[c][0.95\textheight][t]{0.69\linewidth}

%---------------------------------------------------------------------------------------
%	TITLE HEADLINE
%----------------------------------------------------------------------------------------
\vspace{-15pt} % I changed this!


% use this for single words, e.g. CV or RESUME etc.
\colorbox{bgcol}{\makebox[\mpwidth][c]{\HUGE{\textcolor{white}{\uppercase{Johannes Jestram}} } }}

\vspace{6pt}
%============================================================================%
%
%	CV SECTIONS AND EVENTS (MAIN CONTENT)
%
%============================================================================%

%---------------------------------------------------------------------------------------
%	STATUS
%----------------------------------------------------------------------------------------
\cvsection{Über mich}
...
```
However, this leads to a white bar showing in the middle of the header bar.
![grafik](https://user-images.githubusercontent.com/17967115/150755387-a3753a28-7924-4e4f-98c6-200690a143fd.png)

## Expected Behavior
No white bar crossing my name.

## What I tried
- Removed the image on the right
- Moved the headerbar a bit further down - **the line remains in the exact same place, i.e., if I move the header bar down far enough, the white line no longer crosses it**. Does it have something to to with the page layout maybe, e.g.,some padding boundary?

Do you have any ideas how to get rid of the white line?

**Comment by jankapunkt** [comment]
This is very likely to be the border of some other box maybe? The whole `vspace` is very problematic and destroys layout quickly when boxes change.

Does it remove the line when you add the RESUME headline?

```
\colorbox{bgcol}{\makebox[\mpwidth][c]{\HUGE{\textcolor{white}{\uppercase{Johannes Jestram}} } \textcolor{sectcol}{\rule[-1mm]{1mm}{0.9cm}} \HUGE{\textcolor{white}{\uppercase{Resume}}} }}
```

**Comment by jo-jstrm** [comment]
Thanks for your reply. Unfortunately, adding the RESUME headline did not make the white line disappear.

However, I solved it:
- Change height of both minipages to 0.98: `\fcolorbox{white}{white}{\begin{minipage}[c][0.98\textheight][t]{0.69\linewidth}`.
- Now `\vspace{-3pt}` suffices for alignment, probably without moving out of bounds of a box
- I think the white line was the box of the left minipage

### Code
```
\begin{document}
\fcolorbox{white}{white}{\begin{minipage}[c][0.98\textheight][t]{0.69\linewidth}

%---------------------------------------------------------------------------------------
%	TITLE HEADLINE
%----------------------------------------------------------------------------------------
\vspace{-3pt}


% use this for single words, e.g. CV or RESUME etc.
\colorbox{bgcol}{\makebox[\mpwidth][c]{\HUGE{\textcolor{white}{\uppercase{Johannes Jestram}} } }}

% ...

\end{minipage}}
\fcolorbox{white}{sectcol}{\begin{minipage}[c][0.98\textheight][t]{0.33\linewidth}

\begin{figure}[H] 
% my image

%...
```

### Result
![grafik](https://user-images.githubusercontent.com/17967115/150992952-2a54d346-2084-43e3-9541-094f8e6fdba3.png)
