### ISSUE TITLE
Question about Modern CV

### ISSUE THREAD

**Issue by jacksongazin2022** [jankapunkt/latexcv#56]
How would you make a new type of CV event so so there would be three bullet points instead of one?
Right now I have \newcommand{\cveventt}[5]
{
\vspace{8pt}
	\begin{tabular*}{0.6\linewidth}{ p{12cm} x{3cm}}
\textbf{#2} \textcolor{bgcol}{(#3)}&\textcolor{bgcol}{#1}\\[4pt]
	\end{tabular*}
\vspace{-12pt}
\textcolor{softcol}{\hrule}
\vspace{6pt}
	\begin{tabular*}{1\textwidth}{l}
		 \larrow{sectcol}  #4\\[4.5pt]
		 \larrow{sectcol}  #5\\[4.5 pt]
		 \larrow{sectcol}  #6\\[6 pt]
	\end{tabular*}
\vspace{-4pt}
}

but it is not working.

Thanks so much.

**Comment by jankapunkt** [comment]
Hey @jacksongazin2022 there has been a pull request, that added variable bullets to cvevents in the classic cv: https://github.com/jankapunkt/latexcv/pull/37

Maybe this helps you further?
