### ISSUE TITLE
Dynamics with longer words / names

### ISSUE THREAD

**Issue by Lukas2112** [jankapunkt/latexcv#60]
A. Problem / Goal

People with double names, e.g. "Schmidt-Müller", could have the problem that their first name and surname are altogether too long when using the template. 

The aim would be to provide enough space for people with longer names or for e.g. job titles.

### B. Solution

A workaround in the .tex files that takes effect when longer names or terms are entered, which makes it possible to enter longer names or e.g. complete job titles without destroying the formatting of the template.

Conceivable would be either that the font becomes smaller with more text or a new line is created.

### C. Alternatives
Templates for people with longer names cannot be used

**Comment by jankapunkt** [comment]
Thanks @Lukas2112 for the proposal. Please keep in mind that the top premise of this repo is to provide simple, self contained templates. I'd rather have users customize the existing templates to their needs.

Is there a way in LaTeX to autofit text to the parent container without any additional environment like luatex, xetex, coma etc.?
