### ISSUE TITLE
Docker image with prepared LaTeX installation and GitHub action which run it

### ISSUE THREAD

**Issue by marcindabrowski** [jankapunkt/latexcv#64]
Hi,
What about creating Docker image with installed LaTeX? You can publish it to [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

Then you can also prepare GitHub Action which can be run to generate CV using this Docker.

WDYT?

**Comment by jankapunkt** [comment]
Sounds interesting. The image would be > 1GB though, would that be a problem?

**Comment by jankapunkt** [comment]
@marcindabrowski friendly ping :-) is #65 providing what you need?
